_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_stickersnovelshot_tinyonly/model_reset_surgery.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 44
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  #TRAIN: ('30_tinyonly',)
  TRAIN: ('tinyonly_stickers_31shot_1400', '30_tinyonly')
  TEST: ('stickers_31shot_1400_test',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (216000,)
  MAX_ITER: 4000
  CHECKPOINT_PERIOD: 9000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/stickers/stickers_31shot_tinyonly_16_random_all"