_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/base/coco/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 2
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('stickers_fewshot',)
  TEST: ('stickers_28shot_test',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (216000,)
  MAX_ITER: 128000
  CHECKPOINT_PERIOD: 12000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/stickers/stickers_28shot2classes_18000iters_onbase_lr001"