_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
# checkpoints/stickers/stickers_31shot_tinyonly_top4_8_random_all_5000iters_lr001_unfreeze/checkpoint
# BEST WINDSHIELD SO FAR take note
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_stickersnovelshot_tinyonly_top4classes/model_reset_surgery.pth"
  ANCHOR_GENERATOR:
    SIZES: [[8], [16], [32], [64], [128]]
    #SIZES: [[32], [64], [128], [256], [512]]
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
    BATCH_SIZE_PER_IMAGE: 256
    OUTPUT_LAYER: "CosineSimOutputLayers"
    # 0.20 or 0.05
    SCORE_THRESH_TEST: 0.05
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 14
  RPN:
   POST_NMS_TOPK_TRAIN: 2000
 #   FREEZE_FEAT: True
  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5
 #   FREEZE: True
 # PROPOSAL_GENERATOR:
 #   FREEZE: True

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1200

DATASETS:
  #TRAIN: ('30_tinyonly',)
  TRAIN: ('tinyonly_top4_stickers_31shot_1280', '30_tinyonly_top4')
  # stickers_31shot_1280_test_top4
  TEST: ('stickers_31shot_1280_test_tinyonly_top4',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (500,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 100
  WARMUP_ITERS: 10
# checkpoints/stickers/stickers_31shot_tinyonly_top4_8_random_all_5000iters_lr001_unfreeze/checkpoint
OUTPUT_DIR: "results/stickers_only/31shot/with_steps_500"