_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
# checkpoints/stickers/stickers_31shot_tinyonly_top4_8_random_all_5000iters_lr001_unfreeze/checkpoint
# copied the best config, then changed the dataset to the cropped windshields
# weights for tiny only top 4 + stickers: checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_stickersnovelshot_tinyonly_top4classes/model_reset_surgery.pth
  WEIGHTS: "checkpoints/coco/faster_rcnn/faster_rcnn_R_101_FPN_stickersnovelshot_tinyonly_top4classes/model_reset_surgery.pth"
  ANCHOR_GENERATOR:
    SIZES: [[8], [8], [16], [16], [24]]
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 5
    BATCH_SIZE_PER_IMAGE: 64
    OUTPUT_LAYER: "CosineSimOutputLayers"
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 14
  RPN:
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5

INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1200
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1200

  
DATASETS:
  TRAIN: ('crop_stickers_tinyonly_top4_train', '30_tinyonly_top4')
  TEST: ('crop_stickers_tinyonly_top4_test',)

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.001
  STEPS: (216000,)
  MAX_ITER: 1000 
  CHECKPOINT_PERIOD: 100
  WARMUP_ITERS: 10
# checkpoints/stickers/stickers_31shot_tinyonly_top4_8_random_all_5000iters_lr001_unfreeze/checkpoint
OUTPUT_DIR: "results/train_wscs_results"